// Generated by CoffeeScript 1.10.0
(function() {
  Polymer({
    is: "cordova-battery",
    properties: {
      isPlugged: {
        readOnly: true,
        reflectToAttribute: true,
        type: Boolean
      },
      level: {
        readOnly: true,
        reflectToAttribute: true,
        type: Number
      }
    },
    _statusChanged: function(info) {
      this._setIsPlugged(info.isPlugged);
      return this._setLevel(info.level);
    },
    attached: function() {
      window.addEventListener("batterystatus", this._statusChanged.bind(this), false);
      window.addEventListener("batterylow", this.fire.bind(this, "cordova-battery-low", this.level), false);
      return window.addEventListener("batterycritical", this.fire.bind(this, "cordova-battery-critical", this.level), false);
    },
    detached: function() {
      window.removeEventListener("batterystatus", this._batteryChanged);
      window.removeEventListener("batterylow", this.fire);
      return window.removeEventListener("batterycritical", this.fire);
    }
  });

}).call(this);

//# sourceMappingURL=cordova-battery.js.map
